export const INITIAL_VARIANT_ID = 1;
export const DEFAULT_VARIANT_PRICE = 0;
export const FIRST_IMAGE_INDEX = 0;
export const PRICE_ARRAY_DEFAULT_LENGTH = 0;
export const FRACTION_DIGITS_COUNT_DEFAULT = 2;